---
Name: socialnavconfig
---
## YML Config
SilverStripe\Control\Controller:
  extensions:
    - 'ilateral\SilverStripe\SocialNav\Extensions\ControllerExtension'
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - 'ilateral\SilverStripe\SocialNav\Extensions\SiteConfigExtension'

